# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1XAYk6d-Bc0DbFMcAJcuPujbC5Ca1y-
"""

# ======================================
#  SISTEMA DE ESTUDIANTES (versión interactiva)
# ======================================

estudiantes = []

# ---------------- FUNCIONES ----------------
def agregar_estudiante(nombre, edad, promedio, materias, grado):
    estudiante = {
        "nombre": nombre,
        "edad": edad,
        "promedio": promedio,
        "materias": materias,
        "grado": grado,
    }
    estudiantes.append(estudiante)
    print(f" Estudiante '{nombre}' agregado correctamente.")


def buscar_estudiante(nombre):
    for estudiante in estudiantes:
        if estudiante["nombre"].lower() == nombre.lower():
            return estudiante
    return None


def eliminar_estudiante(nombre):
    estudiante = buscar_estudiante(nombre)
    if estudiante:
        estudiantes.remove(estudiante)
        print(f" Estudiante '{nombre}' eliminado correctamente.")
    else:
        print(f" No se encontró el estudiante '{nombre}'.")


def actualizar_estudiante(nombre):
    estudiante = buscar_estudiante(nombre)
    if estudiante:
        print(f" Actualizando información de '{nombre}'...")
        nueva_edad = input("Nueva edad (dejar vacío para mantener): ")
        nuevo_promedio = input("Nuevo promedio (dejar vacío para mantener): ")
        nuevo_grado = input("Nuevo grado (dejar vacío para mantener): ")

        if nueva_edad:
            estudiante["edad"] = int(nueva_edad)
        if nuevo_promedio:
            estudiante["promedio"] = float(nuevo_promedio)
        if nuevo_grado:
            estudiante["grado"] = nuevo_grado

        print(f" Información de '{nombre}' actualizada correctamente.")
    else:
        print(f" No se encontró el estudiante '{nombre}'.")


def calcular_promedio_general():
    if not estudiantes:
        return 0
    total = sum(est["promedio"] for est in estudiantes)
    return total / len(estudiantes)


def mostrar_todos():
    if not estudiantes:
        print(" No hay estudiantes registrados.")
        return
    print("\n === LISTA DE ESTUDIANTES ===")
    for est in estudiantes:
        print(f"{est['nombre']} | Edad: {est['edad']} | Promedio: {est['promedio']} | Grado: {est['grado']}")
    print("=====================================")


# ---------------- MENÚ PRINCIPAL ----------------
def menu():
    while True:
        print("\n MENÚ PRINCIPAL")
        print("1️  Agregar estudiante")
        print("2️  Eliminar estudiante")
        print("3  Actualizar información")
        print("4️  Mostrar todos")
        print("5️  Calcular promedio general")
        print("6️  Salir")

        opcion = input(" Elige una opción (1-6): ")

        if opcion == "1":
            nombre = input("Nombre: ")
            edad = int(input("Edad: "))
            promedio = float(input("Promedio: "))
            materias = input("Materias (separadas por comas): ").split(",")
            grado = input("Grado: ")
            agregar_estudiante(nombre, edad, promedio, materias, grado)

        elif opcion == "2":
            nombre = input("Nombre del estudiante a eliminar: ")
            eliminar_estudiante(nombre)

        elif opcion == "3":
            nombre = input("Nombre del estudiante a actualizar: ")
            actualizar_estudiante(nombre)

        elif opcion == "4":
            mostrar_todos()

        elif opcion == "5":
            promedio = calcular_promedio_general()
            print(f" Promedio general del grupo: {round(promedio, 2)}")

        elif opcion == "6":
            print(" Saliendo del programa...")
            break

        else:
            print(" Opción no válida. Intenta nuevamente.")


# ---------------- EJECUCIÓN ----------------
menu()